use empresaCJ3037916;

CREATE TABLE DEPENDENTES (
    CodDependentes INT PRIMARY KEY,
    Nome VARCHAR(35) NOT NULL,
    Sexo CHAR(1) NULL,
    DataNascimento DATE NOT NULL,
    ID INT FOREIGN KEY REFERENCES
FUNCIONARIOS (ID)
);

SELECT * FROM DEPENDENTES;

SET DATEFORMAT YMD;

BULK INSERT DEPENDENTES
    FROM '/dados/dependentes.csv'
WITH(
    FIRSTROW = 2,
    DATAFILETYPE = 'widechar',
    FIELDTERMINATOR = ','
);

SELECT * FROM DEPENDENTES;
SELECT * FROM FUNCIONARIOS;

CROSS JOIN 